name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_PEM_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Add server public key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -T -i private_key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -x
            export DOCKERHUB_USERNAME="${{ secrets.DOCKERHUB_USERNAME }}"
            export COMMIT_ID="${{ github.sha }}"
            cd /home/ubuntu/react-app || mkdir -p /home/ubuntu/react-app
            cd /home/ubuntu/react-app
            git init || true
            git remote add origin https://github.com/renownjhoe/Task_Test_Josimar_Frontend_CI_CD_Deployment.git || true
            git fetch || true
            git checkout main || true
            git pull origin main || true
            docker compose down || true
            docker compose up -d --build || { echo "docker compose up failed"; exit 1; }
            docker network ls
            docker network inspect app-network
            docker ps
          EOF

      - name: Clean up SSH key
        run: rm -f private_key.pem
        if: always()

      - name: Clean up known_hosts file
        run: |
          rm -f ~/.ssh/known_hosts
        if: always()

  monitoring_check:
    name: Verify Monitoring Services
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Add server public key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ env.SERVER_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_PEM_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Check Prometheus Service
        run: |
          ssh -T -i private_key.pem ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} << 'EOF'
            set -x
            cd /home/ubuntu/Task_Test_Josimar_Backend
            echo "Checking if Prometheus is running..."
            docker logs prometheus || true
          EOF

      - name: Check Grafana Service
        run: |
          ssh -T -i private_key.pem ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} << 'EOF'
            set -x
            cd /home/ubuntu/Task_Test_Josimar_Backend
            echo "Checking if Grafana is running..."
            docker logs grafana || true
          EOF